version: '3.4'

services:
  concept2logbookhelper.server:
    image: reblou/concept2logbookhelperserver
    build:
      context: .
      dockerfile: Concept2LogbookHelper.Server/Dockerfile
    ports:
      - 51803:80
      - 44360:443
    environment:
        - ConnectionStrings__Redis=redis:5111
        - ASPNETCORE_URLS=https://+:443;http://+:80
  redis:
    image: redis
    command: --port 5111
    container_name: redis